spring:
  application:
    name: discovery
server:
  port: 4400
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4400/eureka
    enabled: true
management:
    security:
        enabled: false
    endpoints:
        web:
        exposure:
            include: "*"
        health:
        show-details: ALWAYS
