server:
  port: 4411

spring:
  config:
    activate:
      on-profile: dev,prod
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-service
    name: redis-config,transaction-service
  application:
    name: transaction-management-service

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 60
  client:
    service-url:
      defaultZone: http://localhost:4400/eureka
management:
  endpoints:
    web:
      exposure:
      include: "*"
  endpoint:
    health:
      show-details: ALWAYS